### ISSUE TITLE
Gem is broken: `NameError: uninitialized constant RequestVia::VERSION`

### ISSUE THREAD

**Issue by rzaharenkov** [serradura/request_via#2]
It's literally broken:

```
$ gem install request_via
Fetching: request_via-0.5.0.gem (100%)
Successfully installed request_via-0.5.0
Parsing documentation for request_via-0.5.0
Installing ri documentation for request_via-0.5.0
Done installing documentation for request_via after 0 seconds
1 gem installed
$ irb
2.4.1 :001 > require 'request_via'
NameError: uninitialized constant RequestVia::VERSION
```

I think the problem is `func` is required before `version`:

```ruby
require "request_via/func"
require "request_via/version"
```

**Comment by ivan-leschinsky** [comment]
Fix is here: https://github.com/serradura/request_via/pull/1

**Comment by serradura** [comment]
😅 

Thanks, @rzaharenkov for reporting and @ivan-leschinsky for fixing the issue.

I don't understand the why this error doesn't happen in the test suite. 🤔 

I released a new version of this fix.
https://rubygems.org/gems/request_via/versions/0.5.1
